@startuml
abstract class Subject {
    void template()
    {abstract} void method1()
    {abstract} void method2()
}
class Subject1 extends Subject {
    void method1()
    void method2()
}
class Subject2 extends Subject {
    void method1()
    void method2()
}
@enduml