@startuml
class Memento
class Originator {
    Memento snapshot()
    void restore(Memento m)
}
class Caretaker {
    -List<Memento> list
    void put(Memento m)
    Memento get(int step)
}
Originator .right.> Memento
Caretaker .left.> Memento
@enduml