@startuml
interface State {
    void handle(Context ctx, String arg)
}
class State1 implements State
class State2 implements State
class Context {
    -State state
    void transform(String arg)
}
State <.left.> Context
@enduml