@startuml
queue ChannelPipeline {
    object head {
        inbound=false
        outbound=true
    }
    object context1 {
        inbound
        outbound
        handler
    }
    head -right-> context1
    context1 -left-> head
    object context2 {
        inbound
        outbound
        handler
    }
    context1 -right-> context2
    context2 -left-> context1
    object tail {
        inbound=true
        outbound=false
    }
    context2 -right-> tail
    tail -left-> context2
}
@enduml