@startuml
abstract class AbstractAutoProxyCreator implements SmartInstantiationAwareBeanPostProcessor
abstract class AbstractAdvisorAutoProxyCreator extends AbstractAutoProxyCreator
class BeanNameAutoProxyCreator extends AbstractAutoProxyCreator
class AnnotationAwareAspectJAutoProxyCreator extends AspectJAwareAdvisorAutoProxyCreator
class AspectJAwareAdvisorAutoProxyCreator extends AbstractAdvisorAutoProxyCreator
class DefaultAdvisorAutoProxyCreator extends AbstractAdvisorAutoProxyCreator
class InfrastructureAdvisorAutoProxyCreator extends AbstractAdvisorAutoProxyCreator
@enduml