# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy blog on github and gitee

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm run build
    - name: Setup Deploy Private Key
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan gitee.com >> ~/.ssh/known_hosts
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'sunn4room' 
        git config --global user.email '1795999147@qq.com'
    - name: deploy blog
      run: |
        cd .vuepress/dist
        git init
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:sunn4room/sunn4room.github.io.git master
        git push -f git@gitee.com:sunn4room/sunn4room.git master
